language: python
python: 2.7
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
env:
- TOX_ENV=sphinx
install:
- pip install -U pip setuptools
- pip install tox
- python setup.py --version
- pip install -e.[doc]
script:
- tox -e "${TOX_ENV}"
notifications:
  email: false
  slack:
    secure: KReoL12Rn2C47XXC2sDwTOfg8sKPbGCnTJclYCnK7X0sNDwvTpweaLCKeKntQeYmuU70G8Gb+Qd0Ya+SgVhAP8f4GKcrJhzsvF0JTD6v3e5f8afb6pIi7nECNyO01c0tx4iBcbcmFm8ftu+frKmwOzTuLNNPGVf7YUmOpyLb32n47apiX35YQDLj0V+tX1YJJq6ibbxhEqsMLc7e+Fb8p1Zz5ZjiYuU7dd7WHbZCrl6+T/NpkERedmHsvmDgASBmJs6DXJlxWwCMZas/19Hz3z40/V+mBQpZWzyhzDF0OBSHn+fTlYtvz49UMNfGnfUQoeMHnGMrIKLuJzE6cXgIZbSzw2i3TUifFY9+CkLmqO6QnHmqc+o5nv09wsh0zy2vl+IIq2+VJVewSe2LYXpZHd8BDeYDfnp8e0mXQQs23rPJJ7KYP1rOL5wT2NG7YoLlDhdGnvqF4WQ2oSwCcHXRs7BWbxxER0ftDzqoqjH1tPIb/1aKZ+/1Wa698YrfQAvnHvn/bxTGwtyV0tfj8bPqLx5Ir4Z0PKEYli5wcyWlakIe5YSiTbHjvI0Vg9yhozhLQq6+CB6o7hYd2z0pKCI8D2CM8dGWh877hzL3Os9yZI5+LLlClQrGaBEM0lYix+qgy1ihZS1r2PElBpAu90PZQYhXbg5F81xP2IqortoQ2hk=
