language: python
python: 2.7
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOX_ENV=sphinx

install:
  - pip install -U pip setuptools
  - python setup.py --version
  - pip install -e.[doc]

script:
  - tox -e "${TOX_ENV}"

notifications:
  email: false
